import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:merge_odyssey/core/services/firebase_service.dart';
import 'package:merge_odyssey/ui/screens/main_screen.dart';

// NOTE: Firebase configuration files must be added before using Firebase services:
// - Android: Place google-services.json in android/app/
// - iOS: Place GoogleService-Info.plist in ios/Runner/
// - Web: firebase_options.dart will be generated by FlutterFire CLI
// Run: flutterfire configure to generate firebase_options.dart

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp();
  await FirebaseService.instance.initialize();

  runApp(ProviderScope(child: MergeOdysseyApp()));
}

class MergeOdysseyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Merge Odyssey',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MainScreen(),
    );
  }
}
